flyway.url=jdbc:postgresql://localhost:5433/marketplace?gssEncMode=disable

flyway.user=marketplace
flyway.password=marketplace123

flyway.locations=filesystem:db/migration
flyway.schemas=public
flyway.encoding=UTF-8
flyway.validateOnMigrate=true
flyway.placeholderReplacement=false
