flyway.url=jdbc:postgresql://postgres:5432/marketplace?gssEncMode=disable

flyway.user=marketplace
flyway.password=marketplace123

flyway.locations=filesystem:/flyway/sql
flyway.schemas=public
flyway.encoding=UTF-8
flyway.validateOnMigrate=true
flyway.placeholderReplacement=false