const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({headless: true, executablePath: process.env.BROWSER_EXECUTABLE || '/Applications/Yandex.app/Contents/MacOS/Yandex'});
  const page = await browser.newPage({viewport: {width: 1440, height: 1000}});
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(process.env.APP_URL || 'http://127.0.0.1:8000');
  await page.getByRole('button', {name: 'Войти', exact: true}).click();
  await page.getByRole('button', {name: 'Нет аккаунта? Зарегистрироваться'}).click();
  await page.locator('#auth-form [name=email]').fill(`browser-${Date.now()}@example.com`);
  await page.locator('#auth-form [name=password]').fill('browser-test-123');
  await page.getByRole('button', {name: 'Зарегистрироваться', exact: true}).click();
  await page.locator('#auth-dialog').waitFor({state: 'hidden'});
  await page.getByRole('button', {name: '+ Добавить товар'}).click();
  const name = `Лампа Studio ${Date.now()}`;
  await page.locator('#product-form [name=name]').fill(name);
  await page.locator('#product-form [name=description]').fill('Мягкий свет для вечерней работы. <script>alert(1)</script>');
  await page.locator('#product-form [name=price]').fill('2490.50');
  await page.locator('#product-form [name=stock]').fill('12');
  await page.locator('#product-form [name=category]').fill('Свет');
  await page.getByRole('button', {name: 'Сохранить товар'}).click();
  await page.locator('#product-dialog').waitFor({state: 'hidden'});
  let card = page.locator('.card').filter({has: page.getByRole('heading', {name, exact: true})});
  await card.waitFor();
  await card.getByRole('button', {name: 'Подробнее'}).click();
  await page.locator('#detail-dialog').waitFor({state: 'visible'});
  assert((await page.locator('#detail-body').textContent()).includes('<script>alert(1)</script>'));
  await page.locator('#detail-dialog .close').click();
  await card.getByRole('button', {name: 'Изменить'}).click();
  await page.locator('#product-form [name=price]').fill('1990.00');
  await page.getByRole('button', {name: 'Сохранить товар'}).click();
  await page.locator('#product-dialog').waitFor({state:'hidden'});
  await page.waitForFunction(n => [...document.querySelectorAll('.card')].some(c => c.textContent.includes(n) && c.textContent.includes('1 990')), name);
  await page.screenshot({path: `${process.env.SCREENSHOT_DIR || '/tmp'}/marketplace-desktop.png`, fullPage:true});
  await card.getByRole('button', {name: 'В архив'}).click();
  await page.getByRole('button', {name: 'Архивировать', exact: true}).click();
  await page.locator('#delete-dialog').waitFor({state:'hidden'});
  await card.waitFor({state:'hidden'});
  await page.locator('#filters [name=status]').selectOption('ARCHIVED');
  await page.getByRole('button', {name:'Показать', exact:true}).click();
  await card.waitFor();
  await page.setViewportSize({width:390, height:844});
  await page.screenshot({path: `${process.env.SCREENSHOT_DIR || '/tmp'}/marketplace-mobile.png`, fullPage:true});
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByRole('button', {name:'Выйти', exact:true}).click();
  await page.getByRole('button', {name:'Войти', exact:true}).waitFor();
  assert.deepEqual(errors, []);
  console.log('Browser CRUD, detail, archive filter, logout, XSS text and mobile layout: PASS');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
